ch12-04
rust-lang-ru/book pull request #823
Opened 2022-06-06 10:54 UTC by aleksandr-shevchenko

Спасибо за Pull Request!

Для перевода мы используем Gitlocalize. Ссылка на проект
есть в Readme.

2022-06-08 17:08 UTC, aleksandr-shevchenko commented
Почему не принимаете? Какие есть замечания?

2022-06-10 12:51 UTC, ava57r commented
банально не было времени свободного

2022-06-10 12:57 UTC, ava57r commented on rustbook-ru/src/ch08-01-vectors.md
> +Первым типом коллекции, который мы разберём, будет `Vec<T>`, также известный
при переводе не создавайте новых переносов строк иначе ломается синхронизация с огириналом

2022-06-10 12:57 UTC, ava57r commented on rustbook-ru/src/ch08-01-vectors.md
> +<span class="caption">Листинг 8-4. Использование синтаксиса индексации и метода <code>get</code> для доступа к элементу в векторе</span>
```suggestion
<span class="caption">Листинг 8-4. Использование синтаксиса индексации и метода <code>get</code> для доступа к элементу в векторе</span>

```

2022-06-10 13:25 UTC, ava57r requested changes

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch03-05-control-flow.md
> +#### Цикл по элементам коллекции с помощью `for`<a name="looping-through-a-collection-with-for"></a>
нет в оригинале такой ссылки

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch11-01-writing-tests.md
> +### Структура тестирующей функции<a name="the-anatomy-of-a-test-function"></a>
нет в оригинале такой ссылки

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +Поскольку они нам больше не нужны, давайте удалим строки с `println!`, которые мы использовали для проверки поведения программы в *src/lib.rs* и *src/main.rs*. Затем в *src/lib.rs* мы добавим модуль
```suggestion
Поскольку они нам больше не нужны, давайте удалим строки с `println!`, которые мы использовали для проверки поведения программы в *src/lib.rs* и *src/main.rs*. Затем в *src/lib.rs* мы добавим модуль `tests` с тестовой функцией, как делали это в [главе 11][ch11-anatomy]<!-- ignore -->. Тестовая функция определяет поведение, которое мы хотим проверить в функции `search`. Она должна принимать запрос и текст для поиска, а возвращать только те строки из текста, которые содержат запрос. В листинге 12-15 показан этот тест, он пока не компилируется.
```

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +Заметьте, что в сигнатуре `search` нужно явно указать время жизни `'a` для аргумента `contents` и возвращаемого значения. Напомним из [Главы 10][ch10-lifetimes], что параметры времени жизни указывают
```suggestion
Заметьте, что в сигнатуре `search` нужно явно указать время жизни `'a` для аргумента `contents` и возвращаемого значения. Напомним из [Главы 10][ch10-lifetimes]<!-- ignore -->, что параметры времени жизни указывают с временем жизни какого аргумента связано время жизни возвращаемого значения. В данном случае мы говорим, что возвращаемый вектор должен содержать срезы строк, ссылающиеся на содержимое аргумента `contents` (а не аргумента `query`).
```

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +Другие языки программирования не требуют от вас связывания в сигнатуре аргументов с возвращаемыми значениями. Хотя сейчас это может показаться странным, со временем станет понятнее. Можете сравнить э
```suggestion
Другие языки программирования не требуют от вас связывания в сигнатуре аргументов с возвращаемыми значениями. Хотя сейчас это может показаться странным, со временем станет понятнее. Можете сравнить этот пример с разделом [«Валидация ссылок при помощи времён жизни»][validating-references-with-lifetimes]<!-- ignore --> главы 10.
```

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +Метод `lines` возвращает итератор. Мы подробно поговорим об итераторах в [Главе 13][ch13-iterators], но вспомните, что вы видели этот способ использования итератора в [Листинге 3-5][ch3-iter], где мы
```suggestion
Метод `lines` возвращает итератор. Мы подробно поговорим об итераторах в [Главе 13][ch13-iterators]<!-- ignore -->, но вспомните, что вы видели этот способ использования итератора в [Листинге 3-5][ch3-iter]<!-- ignore -->, где мы использовали цикл `for` с итератором, чтобы выполнить некоторый код для каждого элемента в коллекции.
```

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +На этом этапе мы могли бы рассмотреть возможности изменения реализации функции поиска, сохраняя прохождение тестов и поддерживая имеющуюся функциональность. Код в функции поиска не так уж плох, но он
```suggestion
На этом этапе мы могли бы рассмотреть возможности изменения реализации функции поиска, сохраняя прохождение тестов и поддерживая имеющуюся функциональность. Код в функции поиска не так уж плох, но он не использует некоторые полезные функции итераторов. Вернёмся к этому примеру в [главе 13][ch13-iterators]<!-- ignore -->, где будем исследовать итераторы подробно, и посмотрим как его улучшить.
```

2022-06-10 13:25 UTC, ava57r commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +Поскольку они нам больше не нужны, давайте удалим строки с `println!`, которые мы использовали для проверки поведения программы в *src/lib.rs* и *src/main.rs*. Затем в *src/lib.rs* мы добавим модуль
эти ignore нужны

2022-06-10 17:45 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch03-05-control-flow.md
> +#### Цикл по элементам коллекции с помощью `for`<a name="looping-through-a-collection-with-for"></a>
есть ссылка на этот раздел, поэтому вставляю пустую метку

2022-06-10 17:45 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch10-03-lifetime-syntax.md
> +## Валидация ссылок при помощи времён жизни<a name="validating-references-with-lifetimes"></a>
есть ссылка на этот раздел, поэтому вставляю пустую метку

2022-06-10 17:45 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch11-01-writing-tests.md
> +### Структура тестирующей функции<a name="the-anatomy-of-a-test-function"></a>
есть ссылка на этот раздел, поэтому вставляю пустую метку

2022-06-10 17:47 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch12-04-testing-the-librarys-functionality.md
> +Поскольку они нам больше не нужны, давайте удалим строки с `println!`, которые мы использовали для проверки поведения программы в *src/lib.rs* и *src/main.rs*. Затем в *src/lib.rs* мы добавим модуль
Зачем, если не секрет? Я видел и переведенные игноры и пустые(без слова ignore)...

2022-06-10 17:51 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch08-01-vectors.md
> +Первым типом коллекции, который мы разберём, будет `Vec<T>`, также известный
Вопрос как ломается, если оригинал разбит на строки по 70-80символов, между абзацами пустая строка. А в русском варианте абзац - это одна строка. и тоже пустая строка между абзацами.

2022-06-10 17:54 UTC, aleksandr-shevchenko commented
Примите как есть, если надо игноры вставим потом, хотя у меня mdbook не ругается на отсутствие игноров. Пустые ссылки(анкоры) тоже нужны. Потому как русский текст может поменяться, а анкор останется и ссылка будет рабочей.

2022-06-11 09:20 UTC, ava57r commented
> Примите как есть, если надо игноры вставим потом, хотя у меня mdbook не ругается на отсутствие игноров. Пустые ссылки(анкоры) тоже нужны. Потому как русский текст может поменяться, а анкор останется и ссылка будет рабочей.

Если приняли мои предложения, то они уже будут влиты в мастер и потом править не надо будет.

2022-06-11 09:22 UTC, ava57r commented on rustbook-ru/src/ch03-05-control-flow.md
> +#### Цикл по элементам коллекции с помощью `for`<a name="looping-through-a-collection-with-for"></a>
если ссылки нет в оригинале то вставлять свою не стоит. 
Мы перевод делаем в Gitlocalize и такие дополнения просто сломают синхронизацию github и gitlocalize.

2022-06-11 18:36 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch03-05-control-flow.md
> +#### Цикл по элементам коллекции с помощью `for`<a name="looping-through-a-collection-with-for"></a>
В анг.варианте есть ссылки на этот раздел в виде <a href="ch03-05-control-flow.html#looping-through-a-collection-with-for">, где анкор "#looping-through-a-collection-with-for" == имени раздела "#### Looping Through a Collection with `for`". Так работает движок. Будет ли он работать правильно со ссылками на русском языке - не знаю. Но с моим вариантом - работает верно. Я делаю себе локальную копию книги с помощью mdbook. Хотя однажды встретил неработающую русскую ссылку. Изменили в заголовке регистр буквы и ссылка из другого раздела на этот заголовок стала нерабочей.

2022-06-11 18:40 UTC, aleksandr-shevchenko commented on rustbook-ru/src/ch03-05-control-flow.md
> +#### Цикл по элементам коллекции с помощью `for`<a name="looping-through-a-collection-with-for"></a>
И вы не ответили на мои 2 вопроса. Зачем нужно сохранять игноры и почему по вашему ломается синхронизация в гитлокализе если я разобью абза на строки по 70-80 символов как это есть в анг.варианте.

2022-06-14 07:30 UTC, ava57r commented on rustbook-ru/src/ch03-05-control-flow.md
> +#### Цикл по элементам коллекции с помощью `for`<a name="looping-through-a-collection-with-for"></a>
гитлокальз требует сохранения разметки оригинала даже если это комментарии.

2022-06-14 08:08 UTC, merged